title: Welcome to Rara's Site
name: Hazaharah Shadah
email: hazahara.hh@gmail.com
description: This site is flexibel, made by Jekyll and Bootstrap. If you wanna know about this site, 
please visit <a href="https://github.com/hazaharaShadah/">my site</a>.

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: State Islamic University of Sultan Syarif Kasim Riau
project_one_description: State Islamic University of Sultan Syarif Kasim Riau familiar with UIN SUSKA Riau. In this university where I study.
project_one_url: 'https://uin-suska.ac.id/'
project_one_icon: graduation-cap
project_button: UIN SUSKA Riau

project_two: Science and Technology Faculty
project_two_description: Science and Technology Faculty familiar with FASTE.
project_two_url: 'https://fst.uin-suska.ac.id'
project_two_icon: cogs
project_button: FASTE

project_three: Information System
project_three_description: Information System is my departement. We study 2 majors, bussiness and IT.
project_three_url: 'https://sif.uin-suska.ac.id'
project_three_icon: desktop
project_button: Information System

#project_four: Fourth Project
#project_four_description: Describe your project!
#project_four_url: https://github.com/jameshamann/jekyll-material-theme
#project_four_icon: restaurant




github: 'https://github.com/hazaharaShadah'
linkedin: 'https://linkedin.com/in/hazahara-shadah-994290135/'

baseurl: '/Hazahara Shadah' #if your site is located at /blog or /home, enter it here, otherwise leave it as '/'
url: 'http://hazaharaShadah.github.io/' #http://localhost:4000/ #the url of your site

google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
